
language: python

python:
    - 3.8

install:
    - pip install --upgrade pip setuptools wheel psutil pytest
    - pip install -r requirements.txt
    - pip list
    - pip install black flake8
script:
    - flake8 .
    - black -t py38 -l 80
    - pytest -x tests
