
language: python

python:
    - 3.8

install:
    - pip install --upgrade pip setuptools wheel psutil pytest
    - pip install --default-timeout=5000 -q -r requirements.txt
    - pip list
    - pip install pycodestyle
script:
    - pycodestyle .  --max-line-length=80 --ignore=E127,E121,E126,W504
    - pytest -x tests
